# Assign variables
location            = "eastus"
resource_group_name = "linux--remoteexec-rg"
admin_username      = "azureuser"
address_space       = ["10.0.0.0/16"]
vm_image_publisher  = "Canonical"
vm_image_offer      = "UbuntuServer"
vm_image_sku        = "18.04-LTS"
vm_image_version    = "latest"
