# Assign variables
location            = "eastus"
resource_group_name = "linux--remoteexec-rg"
admin_username      = "azureuser"
address_space       = ["10.0.0.0/16"]
vm_image_publisher  = "OpenLogic"
vm_image_offer      = "CentOS"
vm_image_sku        = "7.6"
vm_image_version    = "latest"
