apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          # image: nginxdemos/hello
          image: sonatype/nexus3
          ports:
          - containerPort: 8081
